version: '3.8'

services:
  backend:
    image: backend-app
    ports:
      - "3000:3000"
    env_file:
      - .env  # Aquí se cargarán todas las variables de entorno definidas en el archivo .env
    restart: always
